version: "3.9"

services:

  backend:
    build: .
    container_name: backend2026
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - backend-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mongo-data: